name: GitHub CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
         command="git clone https://github.com/${{ github.repository }} && \ 
                  cd mf_data_locality                                   && \
                  git fetch origin ${{ github.ref }}                    && \ 
                  git checkout FETCH_HEAD                               && \
                  mkdir build                                           && \ 
                  cd build                                              && \ 
                  cmake ..                                              && \ 
                  make -j2"

         # TODO: currently we are not running any tests, we need to identify/
         #   create some quick tests
         echo $command
         docker run -t dealii/dealii:master-focal /bin/sh -c "$command";
